version: '2.5'

services:
  api:
    container_name: pucmg-nodejs-atv2
    build: .
    ports:
      - 3000:3000
    networks:
      - pucmg_nodejs_atv2

  postgres:
    container_name: postgres-db-pucmg-nodejs-atv2
    image: postgres:13-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=dbdigitalwallet
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
    volumes:
      - .:/var/lib/postgresql
    networks:
      - pucmg_nodejs_atv2

networks:
  pucmg_nodejs_atv2:
